name = "love-button"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[vars]
FIREBASE_PROJECT_ID = "lovieapp-b4068"
PERSON_1_NAME = "Giorgos"
PERSON_2_NAME = "Her"

[[d1_databases]]
binding = "DB"
database_name = "love-button"
database_id = "2bf232d6-01d3-4224-aa45-435433e10f60"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "TOKEN_CACHE"
id = "939528e726af44d2b7cd9eeb630e4a02"

[triggers]
crons = []
