package com.lovebutton.app.widget

// GENERATED by scripts/pixel_icons.py — do not edit by hand.
// Regenerate with: python3 scripts/pixel_icons.py
object PixelGrids {
    val GRIDS: Map<String, List<String>> = mapOf(
        "heart" to listOf(
            "...........",
            "..XX...XX..",
            ".XssXXXXXX.",
            "XXsXXXXXXXX",
            "XXXXXXXXXXX",
            "XXXXXXXXXXX",
            ".XXXXXXXXX.",
            "..XXXXXXX..",
            "...XXXXX...",
            "....XXX....",
            ".....X.....",
        ),
        "bubble" to listOf(
            ".XXXXXXXXX.",
            "XXXXXXXXXXX",
            "XXoXXXXXoXX",
            "XXXXXXXXXXX",
            "XXoXXXXXoXX",
            "XXXoooooXXX",
            "XXXXXXXXXXX",
            ".XXXXXXXXX.",
            "..XXXX.....",
            ".XXX.......",
            "XX.........",
        ),
        "paw" to listOf(
            "...XX.XX...",
            "XX.XX.XX.XX",
            "XX.XX.XX.XX",
            "XX.......XX",
            "...........",
            "..XXXXXXX..",
            ".XXXXXXXXX.",
            "XXXXXXXXXXX",
            "XXXXXXXXXXX",
            ".XXXXXXXXX.",
            "..XXXXXXX..",
        ),
        "call" to listOf(
            "..XXX.XXX..",
            "..X...X.X..",
            "..X...XXX..",
            "..X...X.X..",
            "..XXX.X.X..",
            "...........",
            "..X...X....",
            "..X...X....",
            "..X...X....",
            "..X...X....",
            "..XXX.XXX..",
        ),
    )
}
